# What is the goal of your workflow
# Goal is whenever someone changes the python code the linter will check if the syntax, Format , Indentation (linting) is correct or not 

name: Auto linter
on:
  push:
    paths: "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    # This Steps will authomatically clone the code of the current branch into runner 
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7
      # This Step will install python 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
              python-version: '3.14'
      # This Step will install the linter tool 
      - name: Install Linter
        run: pip install ruff
    # This Step will run the linter 
      - name: Check the file for linting
        run: ruff check .
